--- 
cache: 
  directories: 
    - $HOME/.m2
install: true
jdk: openjdk11
language: java
script: "mvn install -DskipTests=false -Dgpg.skip=true -Dmaven.javadoc.skip=true -DargLine=\"-Dlogging.level.root=ERROR\" -B -V"
