package io.mosip.datashare.constant;

public enum ApiName {

	CRYPTOMANAGER_ENCRYPT,

	KEYMANAGER_SIGN,
	
	KEYMANAGER_GET_CERTIFICATE,
	
	KEYMANAGER_UPLOAD_OTHER_DOMAIN_CERTIFICATE,
	
	GET_PARTNER_CERTIFICATE,

	PARTNER_POLICY;
}
